POST http://localhost:3000/users/submit/1

content-type: application/json

{
    "title": "Hello helo",
	"userId": 1,
	"body": "bar",
}
###

# POST http://localhost:3000/users/submit Content-Type: application/json

# PUT http://localhost:3000/users/edit Content-Type: application/json

# PATCH http://localhost:3000/users/patch Content-Type: application/json

# DELETE http://localhost:3000/users/delete